#-----------------------------------------------------------------------------------------------------------------------
# File:  docker-compose.yml
#
# Desc:  Create a Docker container that hosts the Assessment Support Service listening on 32841.
#
# Usage Notes
# ===========
# This docker-compose file expects the following:
#
#   * The sbacoss/tds-assessment-service is already built.  Typically, the sbacoss/tds-assessment-service image is built as part
#     of the Maven build process.  The following command is used to build the .jars and the associated Docker image:
#
#       mvn clean package docker:build -f /path/to/service/pom.xml
#
#   * An enivronment file named assessment-service.env exists in the same directory as this docker-compose file.  The
#     following environment variables should be configured:
#
#       ASSESSMENT_DB_HOST=IP address or FQDN of the MySQL database server that hosts the TDS itembank database
#       ASSESSMENT_DB_PORT=The port on which the MySQL database server listens
#       ASSESSMENT_DB_NAME=The name of the TDS assessments/itembank database (typically "itembank")
#       ASSESSMENT_DB_USER=The MySQL user account with sufficient privileges to read from the itembank database
#       ASSESSMENT_DB_PASSWORD=The password for the MySQL user account
#
#     Due to the sensitive content contained within the assessment-service.env file, it is not (and should not be) checked
#     into source control.
#
#-----------------------------------------------------------------------------------------------------------------------
version: '2'
services:
  assessment:
    image: sbacoss/tds-assessment-service
    ports:
      - "32841:8080"
    environment:
      ASSESSMENT_DB_HOST: ${ASSESSMENT_DB_HOST}
      ASSESSMENT_DB_PORT: ${ASSESSMENT_DB_PORT}
      ASSESSMENT_DB_NAME: ${ASSESSMENT_DB_NAME}
      ASSESSMENT_DB_USER: ${ASSESSMENT_DB_USER}
      ASSESSMENT_DB_PASSWORD: ${ASSESSMENT_DB_PASSWORD}